# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd blue-bank
        mvn clean install -DskipTests

  package_and_upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Package Application
      run: mvn package -DskipTests
      working-directory: blue-bank

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: blue-bank-jar
        path: blue-bank/target/*.jar
        
  # code_quality:
  #   runs-on: ubuntu-latest
  #   needs: package_and_upload
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '21'
  #         distribution: 'temurin'
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@v2
  #       with:
  #         args: >
  #           -Dsonar.projectKey=marcelo-filho_blue-bank
  #           -Dsonar.organization=marcelo-filho-org
  #           -Dsonar.java.binaries=target/
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security_scan:
    runs-on: ubuntu-latest
    needs: package_and_upload
    steps:
      - uses: actions/checkout@v4
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "bluebankI"
          path: "."
          format: "HTML"
          out: "."
      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: dependency-check-report.html
